{
 "title": "Quality Assurance Platform",
 "tags": [ "QAP" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "PROJECT",
    "query": "SELECT project.name FROM project"
   },
   {
    "name": "SPRINT",
    "query": "SELECT sprint.name FROM sprint INNER JOIN project ON sprint.project = project.uuid WHERE project.name = '$PROJECT';"
   },
   {
    "name": "FEATURE",
    "query": "SELECT UNNEST(sprint.features) FROM sprint INNER JOIN project ON sprint.project = project.uuid WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT';"
   },
   {
    "name": "START_DATE",
    "query": "SELECT to_char(capture_at, 'YYYY-MM-DD') FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint WHERE sprint.name = '$SPRINT'  order by 1 limit 1"
   },
   {
    "name": "END_DATE",
    "query": "SELECT to_char(capture_at, 'YYYY-MM-DD') FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint WHERE sprint.name = '$SPRINT'  order by 1 DESC limit 1"
   }
  ]
 },
 "panels": [
  { "title": "Project $PROJECT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$PROJECT Bug In Release Testing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_project_latest.capture_at AS \"time\", sprint.name AS \"Sprint\", cast(issue_project_latest.categories::json->>'total' AS integer) FROM issue_project_latest INNER JOIN sprint ON issue_project_latest.sprint = sprint.uuid INNER JOIN project ON sprint.project = project.uuid WHERE project.name = '$PROJECT' ORDER BY 2\n"
    }
   ]
  },
  {
   "title": "$PROJECT Bug From Customer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_customer_latest.capture_at AS \"time\", sprint.name, issue_customer_latest.count FROM issue_customer_latest INNER JOIN sprint ON sprint.uuid = issue_customer_latest.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' ORDER BY 1"
    }
   ]
  },
  {
   "title": "Sprint $SPRINT ( $START_DATE ~ $END_DATE )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "$SPRINT  Bug Verification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_sprint.capture_at AS \"time\", CAST(issue_sprint.status::json->>'verified' AS integer) AS \"Verified\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_sprint.capture_at AS \"time\", CAST(issue_sprint.status::json->>'fixed' AS integer) AS \"To Be Verified\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_sprint.capture_at AS \"time\", CAST(issue_sprint.status::json->>'fixing' AS integer) AS \"To Be Fixed\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    }
   ]
  },
  {
   "title": "$SPRINT  Bug Categories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_at), CAST(issue_sprint.categories::json->>'newfeature' AS integer) AS \"New Feature\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_at), CAST(issue_sprint.categories::json->>'previous' AS integer) AS \"Previous\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_at), CAST(issue_sprint.categories::json->>'regression' AS integer) AS \"Regression\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_at), CAST(issue_sprint.categories::json->>'others' AS integer) AS \"Others\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    }
   ]
  },
  {
   "title": "$SPRINT  Bug Found In RC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_sprint_latest.capture_at AS \"time\", issue_sprint_latest.rc, issue_sprint_latest.count FROM issue_sprint_latest INNER JOIN sprint ON sprint.uuid = issue_sprint_latest.sprint INNER JOIN project ON project.uuid = sprint.project WHERE sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 2"
    }
   ]
  },
  {
   "title": "$SPRINT Bug Found Since",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_sprint.capture_at AS \"time\", CAST(issue_sprint.found_since::json->>'regression_improve'  AS integer)AS \"Regression Improve\", CAST(issue_sprint.found_since::json->>'new_feature'  AS integer)AS \"New Feature\", CAST(issue_sprint.found_since::json->>'qa_missed' AS integer) AS \"QA Missed\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1 DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "$SPRINT  New Feature Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_feature_latest.capture_at AS \"time\", issue_feature_latest.name, CAST(issue_feature_latest.status::json->>'total' AS integer) FROM issue_feature_latest INNER JOIN sprint ON sprint.uuid = issue_feature_latest.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 3 DESC"
    }
   ]
  },
  { "title": "Feature $FEATURE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$FEATURE  Bug Verification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_feature.capture_at AS \"time\", CAST(issue_feature.status::json->>'verified' AS integer) AS \"Verified\" FROM issue_feature INNER JOIN sprint ON sprint.uuid = issue_feature.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_feature.name = '$FEATURE' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_feature.capture_at AS \"time\", CAST(issue_feature.status::json->>'fixed' AS integer) AS \"To Be Verified\" FROM issue_feature INNER JOIN sprint ON sprint.uuid = issue_feature.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_feature.name = '$FEATURE' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_feature.capture_at AS \"time\", CAST(issue_feature.status::json->>'fixing' AS integer) AS \"To Be Fixed\" FROM issue_feature INNER JOIN sprint ON sprint.uuid = issue_feature.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_feature.name = '$FEATURE' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    }
   ]
  }
 ]
}