{
 "title": "QSphere Sprint",
 "tags": [ "QSphere" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "PROJECT",
    "query": "SELECT project.name FROM project ORDER BY 1"
   },
   {
    "name": "SPRINT",
    "query": "SELECT sprint.name FROM sprint INNER JOIN project ON sprint.project = project.uuid WHERE project.name = '$PROJECT' ORDER BY 1 DESC;"
   },
   {
    "name": "REQUIREMENT",
    "query": "SELECT UNNEST(sprint.requirements) FROM sprint INNER JOIN project ON sprint.project = project.uuid WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT';"
   },
   {
    "name": "START_DATE",
    "query": "SELECT to_char(capture_time, 'YYYY-MM-DD') FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint WHERE sprint.name = '$SPRINT'  order by 1 limit 1"
   },
   {
    "name": "END_DATE",
    "query": "SELECT to_char(capture_time, 'YYYY-MM-DD') FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint WHERE sprint.name = '$SPRINT'  order by 1 DESC limit 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Sprint $SPRINT ( $START_DATE ~ $END_DATE )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "$SPRINT  Bug Verification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_sprint.capture_time AS \"time\", CAST(issue_sprint.status::json->>'verified' AS integer) AS \"Verified\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_sprint.capture_time AS \"time\", CAST(issue_sprint.status::json->>'fixed' AS integer) AS \"To Be Verified\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_sprint.capture_time AS \"time\", CAST(issue_sprint.status::json->>'fixing' AS integer) AS \"To Be Fixed\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    }
   ]
  },
  {
   "title": "$SPRINT Bug Categories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_time), CAST(issue_sprint.categories::json->>'newfeature' AS integer) AS \"New Feature\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_time), CAST(issue_sprint.categories::json->>'previous' AS integer) AS \"Previous\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_time), CAST(issue_sprint.categories::json->>'regression' AS integer) AS \"Regression\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_sprint.capture_time), CAST(issue_sprint.categories::json->>'others' AS integer) AS \"Others\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    }
   ]
  },
  {
   "title": "$SPRINT  Bug Found In RC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_sprint_latest.capture_time AS \"time\", issue_sprint_latest.rc, issue_sprint_latest.count FROM issue_sprint_latest INNER JOIN sprint ON sprint.uuid = issue_sprint_latest.sprint INNER JOIN project ON project.uuid = sprint.project WHERE sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 2"
    }
   ]
  },
  {
   "title": "$SPRINT Bug Found Since",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_sprint.capture_time AS \"time\", CAST(issue_sprint.found_since::json->>'regressionimprove' AS integer)AS \"Regression Improve\", CAST(issue_sprint.found_since::json->>'newfeature' AS integer)AS \"New Feature\", CAST(issue_sprint.found_since::json->>'qamissed' AS integer) AS \"QA Missed\" FROM issue_sprint INNER JOIN sprint ON sprint.uuid = issue_sprint.sprint INNER JOIN project ON project.uuid = sprint.project WHERE sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1 DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "$SPRINT New Feature Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_req_latest.capture_time AS \"time\", issue_req_latest.name, CAST(issue_req_latest.status::json->>'total' AS integer) FROM issue_req_latest INNER JOIN sprint ON sprint.uuid = issue_req_latest.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 3 DESC"
    }
   ]
  },
  { "title": "Requirement $REQUIREMENT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$REQUIREMENT Bug Verification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_req.capture_time AS \"time\", CAST(issue_req.status::json->>'verified' AS integer) AS \"Verified\" FROM issue_req INNER JOIN sprint ON sprint.uuid = issue_req.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_req.name = '$REQUIREMENT' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_req.capture_time AS \"time\", CAST(issue_req.status::json->>'fixed' AS integer) AS \"To Be Verified\" FROM issue_req INNER JOIN sprint ON sprint.uuid = issue_req.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_req.name = '$REQUIREMENT' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_req.capture_time AS \"time\", CAST(issue_req.status::json->>'fixing' AS integer) AS \"To Be Fixed\" FROM issue_req INNER JOIN sprint ON sprint.uuid = issue_req.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_req.name = '$REQUIREMENT' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    }
   ]
  }
 ]
}