FROM python:3.8-alpine3.12
LABEL maintainer="v.stone@163.com"

WORKDIR /workspace
COPY requirements.txt .

RUN apk add --no-cache --update libpq \
    && apk add --no-cache --virtual temp-apks \
        gcc g++ tzdata musl-dev python-dev postgresql-dev libffi-dev rust \
    && python -m pip install --upgrade pip \
    && pip install -r requirements.txt \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone \
    && apk del temp-apks
