FROM python:3.7-alpine3.10
MAINTAINER shiwei@baoxian-sz.com

WORKDIR /workspace
COPY requirements.txt .

RUN apk add --no-cache --update libpq && \
    apk add --no-cache --virtual temp-apks \
        gcc musl-dev python-dev postgresql-dev libffi-dev && \
    pip install -r requirements.txt && \
    apk del temp-apks
